name: Run Data Pipeline
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run data pipeline
      run: |
        mkdir -p ./output/weather
        python fetch.py ./output/weather/stations.csv

    - name: Upload to cloud storage
      uses: azure/CLI@v1
      env:
        AZ_CONTAINER: https://opencovid.blob.core.windows.net/cache
        AZ_STORAGE_KEY: ${{ secrets.AZ_STORAGE_KEY }}
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob upload-batch -d "$AZ_CONTAINER" -s ./output --account-key "$AZ_STORAGE_KEY"
